#! /bin/bash

file_dir=`pwd`
source /afs/cern.ch/user/c/cgoudet/534.sh
start="/afs/cern.ch/work/c/cgoudet/private/"
cd ${file_dir}

cp -v "${start}data/kin_dist.root" ${file_dir}
cp -v "${start}codes/exec/splot_gengghbkg.exe" ${file_dir}
cp -v "${start}data/WS_SPlot.root" ${file_dir}

./splot_gengghbkg.exe 2>logerrorsplot.txt 1>logsplot.txt

rm kin_dist.root
rm splot_gengghbkg.exe
cp WS_SPlot.root "${start}data/."
rm WS_SPlot.root
cp * /afs/cern.ch/work/c/cgoudet/public/BatchDump/.

