#!/bin/bash

batchdir=`pwd`

source ~cgoudet/534.sh
cd ${batchdir}

cp /afs/cern.ch/work/c/cgoudet/private/data/kin_dist.root .
cp /afs/cern.ch/work/c/cgoudet/private/codes/HggKin2/compare_dist2.exe .


./compare_dist2.exe 1>logcompare.txt 2>logerrorcompare.txt

rm kin_dist.root
rm compare_dist2.exe

cp * /afs/cern.ch/work/c/cgoudet/public/BatchDump/.
